export const CURRENCIES: Record<string, { flag: string; name: string }> = {
  USD: { flag: "us", name: "United States Dollar" },
  ILS: { flag: "il", name: "Israeli New Shekel" },
  EUR: { flag: "eu", name: "Euro" },
  HKD: { flag: "hk", name: "Hong Kong Dollar" },
  GBP: { flag: "gb", name: "British Pound Sterling" },
  CAD: { flag: "ca", name: "Canadian Dollar" },
  INR: { flag: "in", name: "Indian Rupee" },
  RUB: { flag: "ru", name: "Russian Ruble" },
  CHF: { flag: "ch", name: "Swiss Franc" },
  JPY: { flag: "jp", name: "Japanese Yen" },
  AED: { flag: "ae", name: "United Arab Emirates Dirham" },
  ARS: { flag: "ar", name: "Argentine Peso" },
  AUD: { flag: "au", name: "Australian Dollar" },
  BDT: { flag: "bd", name: "Bangladeshi Taka" },
  BGN: { flag: "bg", name: "Bulgarian Lev" },
  BHD: { flag: "bh", name: "Bahraini Dinar" },
  BRL: { flag: "br", name: "Brazilian Real" },

  CLP: { flag: "cl", name: "Chilean Peso" },
  CNY: { flag: "cn", name: "Chinese Renminbi" },
  COP: { flag: "co", name: "Colombian Peso" },
  CZK: { flag: "cz", name: "Czech Koruna" },
  DKK: { flag: "dk", name: "Danish Krone" },
  EGP: { flag: "eg", name: "Egyptian Pound" },

  HUF: { flag: "hu", name: "Hungarian Forint" },
  IDR: { flag: "id", name: "Indonesian Rupiah" },

  KRW: { flag: "kr", name: "South Korean Won" },
  KWD: { flag: "kw", name: "Kuwaiti Dinar" },
  LKR: { flag: "lk", name: "Sri Lankan Rupee" },
  MXN: { flag: "mx", name: "Mexican Peso" },
  MYR: { flag: "my", name: "Malaysian Ringgit" },
  NGN: { flag: "ng", name: "Nigerian Naira" },
  NOK: { flag: "no", name: "Norwegian Krone" },
  NZD: { flag: "nz", name: "New Zealand Dollar" },
  OMR: { flag: "om", name: "Omani Rial" },
  PEN: { flag: "pe", name: "Peruvian Sol" },
  PHP: { flag: "ph", name: "Philippine Peso" },
  PKR: { flag: "pk", name: "Pakistani Rupee" },
  PLN: { flag: "pl", name: "Polish Złoty" },
  QAR: { flag: "qa", name: "Qatari Riyal" },
  RON: { flag: "ro", name: "Romanian Leu" },

  SAR: { flag: "sa", name: "Saudi Riyal" },
  SEK: { flag: "se", name: "Swedish Krona" },
  SGD: { flag: "sg", name: "Singapore Dollar" },
  THB: { flag: "th", name: "Thai Baht" },
  TRY: { flag: "tr", name: "Turkish Lira" },
  TWD: { flag: "tw", name: "New Taiwan Dollar" },

  VND: { flag: "vn", name: "Vietnamese Đồng" },
  ZAR: { flag: "za", name: "South African Rand" },
};
